### ISSUE TITLE
-am not adding to repo

### ISSUE THREAD

**Issue by yahwehschica7** [learn-co-curriculum/phase-0-git-version-control-basics#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.
https://learning.flatironschool.com/courses/4409/pages/git-basics?module_item_id=271462
## Describe the bug
I don't know if it is a bug but the -a and the -am are not adding anything to the README.md file. No changes are occurring.
Write a clear and concise description of what the bug is. Include the file and
line number(s) if possible.

## What is the expected behavior?

Write a clear and concise description of what you expected to happen.

## Screenshots

If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X
- [x ] WSL
- [ ] Linux

**Comment by lizbur10** [comment]
Hi there! Thank you for submitting this feedback and apologies for any frustration you encountered.

I have updated the Readme to clarify the use of the `-am` flag, which hopefully will reduce the confusion for future students. Note, however, that the changes may not be reflected in your Canvas course page.

Thanks for contributing to the Flatiron School curriculum! 💙
