### ISSUE TITLE
Git Basics - Final CLI result issue

### ISSUE THREAD

**Issue by vmsuarez93** [learn-co-curriculum/phase-0-git-version-control-basics#2]
### Canvas Link

https://learning.flatironschool.com/courses/4605/pages/git-basics?module_item_id=294952

### Concern

line 209 in the git preview version of the assignment $ git commit -am "Updates README.md" does not give me the final prompt shown in the lesson. My concern is that I may be on an incorrect coding format when I opened up the terminal?

**Comment by lizbur10** [comment]
Hi @vmsuarez93 ! Thanks for bringing this to our attention! If you didn't make any changes to the README file, you wouldn't be able to run that command. I have clarified the instructions in the lesson to try to make that clearer. Note that you may not see in the changes in your Canvas course but it will be present for students moving forward.  💙
