### ISSUE TITLE
Broken Link in 'Git Basics' Pre-Work Lesson

### ISSUE THREAD

**Issue by baspin94** [learn-co-curriculum/phase-0-git-version-control-basics#5]
### Canvas Link

https://learning.flatironschool.com/courses/6150/pages/git-basics?module_item_id=482806

### Concern

In the 'Resources' section of this lesson, the link leading to the 'Git Basics' chapter (https://git-scm.com/book/en/v1/Git-Basics) of Git's 'Pro Git' book is broken, directing to an 'Internal server error' page. It looks like it originally led to an older version of the book.

### Additional Context

Error Page: 
![image](https://user-images.githubusercontent.com/83936508/207994550-86741bc8-f764-4394-9d69-f2d3ed926a28.png)

### Suggested Changes

It looks like this book has been updated since this lesson was originally posted and the link to the 'Git Basics' chapter in the new version is https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository

**Comment by lizbur10** [comment]
Hi @baspin94 ! Thank you for bringing this to our attention and for tracking down the correct link. The link has now been updated. Note that you may not see the correction in your Canvas course, but you can see the new link in the README here in the lesson's repo.

Thanks for contributing to the Flatiron School curriculum 💙
