### ISSUE TITLE
Link Throwing 500 internal server error

### ISSUE THREAD

**Issue by kriegercisneros** [learn-co-curriculum/phase-0-git-version-control-basics#6]
[Git Basics at git-scm.com](https://git-scm.com/book/en/v1/Git-Basics)

This is the one, just thought you should know.

**Comment by lizbur10** [comment]
Hi @kriegercisneros ! Thank you for bringing this to our attention. The link has now been updated. Note that you may not see the correction in your Canvas course, but you can find the new link in the README here in the lesson's repo.

Thanks for contributing to the Flatiron School curriculum 💙
